### ISSUE TITLE
A random resourcepack that boosts FPS from 30 up to 110

### ISSUE THREAD

**Issue by cazpj** [skywardmc/adrenaline#29]
This specific resourcepack boosted my FPS from 30 up to 110:

https://modrinth.com/resourcepack/cleaner-waters

If you guys could investigate, I think it is a great addittion to the modpack

More details:
Resourcepack version: CleanWaters[1.14+]
Minecraft version: fabric 1.20.1

**Comment by MenacingPerson** [comment]
Why did you close this? Did it not actually do that?

**Comment by Phoenix-Starlight** [comment]
This can't actually be the cause of the FPS boost, all it does is change animations and a texture.
It's near impossible for a resource pack to bring any FPS benefits.

**Comment by MenacingPerson** [comment]
@Phoenix-Starlight say what? :P

![image](https://github.com/skywardmc/adrenaline/assets/59611020/7d668529-8d69-4faf-8b49-364bda07734d)

**Comment by Phoenix-Starlight** [comment]
I'd argue it's margin of error and secondly it literally converts grass to a 2d texture.
