### ISSUE TITLE
Entity Culling isn't open source

### ISSUE THREAD

**Issue by jx319** [skywardmc/adrenaline#31]
[The mod's license](https://github.com/tr7zw/EntityCulling#license) specifically disallows redistribution, derivative works and commercial use without explicit permission, which contradicts the [open source definition](https://opensource.org/osd/) (I know there are other definitions as well but they are not that different).
This unfortunately makes the modpack not entirely open source, so either this mod or the goal for the entire pack to be open source should be removed to avoid confusion.
The same issue is also present on Additive since it also includes Entity Culling.

**Comment by TheKodeToad** [comment]
I would personally suggest the phrase "public source" or similar
