### ISSUE TITLE
Enable sodiums entity culling option

### ISSUE THREAD

**Issue by TheNukeLore** [skywardmc/adrenaline#32]
**Is your request related to a problem? Please describe.**
Sodium's entity culling is a fairly effective method in terms of optimizations, it helps even when other mods such as entity culling is present(entity culling can often hurt performance in cases and sodium can help reduce said cases)

**Describe the solution you'd like**
Assuming there are no issues, rein-able the entity culling option in sodium.

**Describe alternatives you've considered**
There are no alternatives I can think of as of this moment.

**Additional context**
I have done some minor testing to see if this setting broke anything and have not found any such cases, however, I was not the most thorough when testing.

**Comment by Uranite** [comment]
Yeah, it should be enabled, I think sodium entity culling was disabled because there is already a mod called entity culling included in the modpack that may seem to do the same thing, but according to the mod developer, it doesn't do the same thing and sodium entity culling should be enabled.
https://github.com/tr7zw/EntityCulling/issues/132#issuecomment-1869783948

**Comment by intergrav** [comment]
Will be done next time I update as I don't see any issues with it - thanks!

**Comment by TheNukeLore** [comment]
Will this also be applied to additive by chance?

**Comment by intergrav** [comment]
Yes. Changes from Adrenaline get applied to Additive as well

**Comment by TheNukeLore** [comment]
Quite honestly, is the sodium config needed at all? Seems the changes it has might just be in default sodium already. Haven’t double checked.

**Comment by intergrav** [comment]
The `cpu_render_ahead_limit` option is different from default Sodium. However, in modern versions of Sodium, `always_defer_chunk_updates` is already set to true (iirc). I'll remove the `always_defer_chunk_updates` line where applicable
