### ISSUE TITLE
Item frame textures not rendering correctly

### ISSUE THREAD

**Issue by hannibal002** [skywardmc/adrenaline#34]
This effect gets bigger and bigger the further apart I move.
I have not changed the default settings of anything.

![image](https://github.com/skywardmc/adrenaline/assets/24389977/da006419-fe03-4ccc-bf23-078fdf693c66)

**Comment by intergrav** [comment]
This seems to be an issue with MoreCulling's custom item frame renderer https://github.com/FxMorin/MoreCulling/issues/199

**Comment by AlexanderwithaA** [comment]
noticed it the same spot i did!
