### ISSUE TITLE
Auto updating instance for 1.20.4 version

### ISSUE THREAD

**Issue by OffsetMonkey538** [skywardmc/adrenaline#37]
**Describe the bug**
It's not possible to have an auto updating instance as packwiz expects the hashes to be present and the https://github.com/skywardmc/additive/commit/6321f3f7c00612ae43670c1d565e484b4db99f67 commit removed them.
One possible solution would be to host a version of the pack generated with `packwiz refresh --build` somewhere.

**To Reproduce**
1. Follow [this guide](https://packwiz.infra.link/tutorials/installing/packwiz-installer/#creating-a-multimc-instance-for-your-modpack) provided by packwiz to setup an instance which automatically updates. For the url use https://raw.githubusercontent.com/skywardmc/additive/main/versions/fabric/1.20.4/pack.toml
2. Press launch.
3. Wait a bit.
4. See error.

**Expected behavior**
I would expect to see packwiz download the mods.

**Screenshots**
![image](https://github.com/skywardmc/additive/assets/71213040/0609faca-1304-4b0e-bc66-4970e2d3d1dc)

**Device info (please complete the following information):**
 - OS: Nobara Linux
 - Minecraft version: 1.20.4

**Comment by intergrav** [comment]
This should now be fixed. Let me know if you run into anymore issues
