### ISSUE TITLE
Noisium

### ISSUE THREAD

**Issue by omo50** [skywardmc/adrenaline#38]
**Is your request related to a problem? Please describe if so.**
N/A

**Describe the mod you'd like to add, remove, or change**
Noisium is a Chunk Performance improving mod, similar to C2ME however less experimental.
It can speed up chunk generation by (according to the mod description) by 20-30%.
https://modrinth.com/mod/noisium

**List alternative mods or solutions you've considered**
C2ME (more experimental, but works in tandem with Noisium)

**Additional context**
N/A

**Comment by intergrav** [comment]
Seems stable enough for use in Adrenaline now, I'll add it :)

**Comment by omo50** [comment]
> Seems stable enough for use in Adrenaline now, I'll add it once I've done a bit of testing :)

Sounds good to me, hope this improves some peoples performance (its shown itself very helpful for me)
