### ISSUE TITLE
Replace More Culling with Cull Less Leaves

### ISSUE THREAD

**Issue by intergrav** [skywardmc/adrenaline#41]
More Culling tends to cause quite a lot of issues with mod compatibility, and can often break certain rendering features in-game. For example, issue #34, and VanillaTweaks’ 3D models breaking. It also hasn’t been definitively proven to improve performance in any major way over Cull Less Leaves.

~~The only issue is that Cull Less Leaves is not updated to versions past 1.20.1. I’d say that a fork could be made with author permission, or I could ask them if they’d be interested in updating to newer versions. Don’t want to bother them though. For now More Culling will stay in the modpack until there’s a solution to the issue.~~

Edit: Cull Less Leaves for 1.20.1 works perfectly fine on latest versions. I will replace next time I update.

**Comment by seriousfreezing** [comment]
I have some doubts, why didn't you just disable by default the features that are giving conflicts in 3D models? And what are the incompatibilities that this mod causes?

**Comment by omo50** [comment]
> I have some doubts, why didn't you just disable by default the features that are giving conflicts in 3D models? And what are the incompatibilities that this mod causes?

The mod can be incompatible/cause issues with many things. It breaks Serene Seasons for example, can mess up item frame rendering, and is full of micro optimizations that really don't do *that* much

**Comment by intergrav** [comment]
> I have some doubts, why didn't you just disable by default the features that are giving conflicts in 3D models? And what are the incompatibilities that this mod causes?

I have seen quite a few issues involving crashing or rendering issues with Serene Seasons, I think Create, and I have personally experienced a few issues with some other mods that I can’t exactly name off the top of my head. It also has issues with resource packs that mess with block models, like Vanilla Tweaks. It also breaks item frame rendering in some cases. If I disable those features that conflict with the models and item frame issues, then there would be no point in even including the mod in the first place since those are the only main unique features it has. Those features haven’t been proven to improve performance in any major way and it’d just be a better choice to use Cull Less Leaves. I do plan on setting CLL’s randomRejection value to 0 so that trees look better, which I forgot to do.

**Comment by seriousfreezing** [comment]
I find it very strange not to find a lot of issues about its incompatibility with other mods, I only had a problem with More Culling with Create itself. I've never noticed much of a difference with it either, but I'd still find it interesting to have its other optimizations - I know it won't be that useful or it'll be a 5% difference in performance or something.
