### ISSUE TITLE
Change BadOptimizations lightmap updates

### ISSUE THREAD

**Issue by dylanspersonal** [skywardmc/adrenaline#45]
As it turns night, the light map darkening is very jittery and noticeable, due to a BadOptimzations feature that updates block lighting less frequently than vanilla.

In badoptimizations.txt, change "lightmap_time_change_needed_for_update" from 80 to 20, which will be a lot less jarring while still giving a performance boost.

**Comment by intergrav** [comment]
sounds good, will look into this sometime, thanks :)
